sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t 2mighty/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 2mighty/docker-react npm run test
