FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# This is to automate rebuilding containers using volumes
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app ed72627d7df0