FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# This is to automate rebuilding containers using volumes
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app ed72627d7df0
# Use this to build the container in dev environment
# docker build -f Dockerfile.dev .
# To run the test
# docker run container_id npm run test
# or use
# docker run -it container_id npm run test
# To run the test live
# Option 1
# docker exec -it {container_id} npm run test
# Option 2
# docker exec -it {container_id} sh
# then run the test in the directory with the command
# npm run test